default: &default
  adapter: postgresql
  encoding: unicode
  pool: 12
  template: template0

development:
  <<: *default
  database: fact_check_manager_development
  url: <%= ENV["DATABASE_URL"]%>

test:
  <<: *default
  database: fact_check_manager_test
  url: <%= ENV["TEST_DATABASE_URL"] %>

# set these environment variables on your prod server
production:
  <<: *default
  database: fact_check_manager_production
  url: <%= ENV["DATABASE_URL"]%>